# Generated by Django 2.2.9 on 2020-04-16 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('varda', '0018_auto_20200408_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('LAPSI_HUOLTAJUUSSUHDE_UPDATE', 'LAPSI_HUOLTAJUUSSUHDE_UPDATE')])),
                ('retry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField()),
                ('henkilo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batcherrors', to='varda.Henkilo')),
            ],
            options={
                'verbose_name_plural': 'batcherrors',
            },
        ),
    ]
